package com.epam.learn.resource_processor.contract;

import com.epam.learn.resource_processor.client.ResourceServiceClient;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.cloud.contract.stubrunner.spring.AutoConfigureStubRunner;
import org.springframework.cloud.contract.stubrunner.spring.StubRunnerProperties;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.web.client.RestTemplate;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatCode;

/**
 * Consumer-side contract test for resource-processor consuming resource-service HTTP API.
 * Uses Spring Cloud Contract Stub Runner to load stubs generated by resource-service producer tests.
 *
 * <p>This test verifies that resource-processor's ResourceServiceClient correctly communicates
 * with resource-service according to the agreed contract.</p>
 *
 * <p>Contract points tested:
 * <ul>
 *   <li>GET /resources/{id} - download resource binary data (audio/mpeg content type)</li>
 * </ul>
 * </p>
 */
@SpringBootTest(
        webEnvironment = SpringBootTest.WebEnvironment.NONE,
        properties = {
                "resource.service.url=http://localhost:8080",
                "song.service.url=http://localhost:8081",
                "eureka.client.enabled=false",
                "spring.cloud.discovery.enabled=false",
                "spring.cloud.loadbalancer.enabled=false",
                "spring.rabbitmq.listener.simple.auto-startup=false",
                "spring.rabbitmq.listener.direct.auto-startup=false",
                "management.health.rabbit.enabled=false"
        }
)
@AutoConfigureStubRunner(
        ids = "com.epam.learn:resource-service:+:stubs:8080",
        stubsMode = StubRunnerProperties.StubsMode.LOCAL
)
@ActiveProfiles("test")
@DisplayName("Resource Processor -> Resource Service Contract Consumer Tests")
class ResourceServiceContractConsumerTest {

    @Autowired
    @Qualifier("resourceServiceRestTemplate")
    private RestTemplate restTemplate;

    @Test
    @DisplayName("Should get resource binary data via GET /resources/{id} contract - verifies audio/mpeg content type")
    void shouldGetResourceDataViaContract() {
        // When - calling resource-service stub directly to verify the contract
        // The contract specifies: GET /resources/1 -> 200 OK with Content-Type: audio/mpeg
        org.springframework.http.ResponseEntity<byte[]> response = restTemplate.getForEntity(
                "/resources/1",
                byte[].class
        );

        // Then - response matches the contract
        assertThat(response.getStatusCode().value()).isEqualTo(200);
        assertThat(response.getHeaders().getContentType()).isNotNull();
        assertThat(response.getHeaders().getContentType().toString()).contains("audio/mpeg");
    }
}
