package com.epam.learn.resource_processor.contract;

import com.epam.learn.resource_processor.client.SongServiceClient;
import com.epam.learn.resource_processor.dto.SongMetadataRequest;
import com.epam.learn.resource_processor.dto.SongMetadataResponse;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.cloud.contract.stubrunner.spring.AutoConfigureStubRunner;
import org.springframework.cloud.contract.stubrunner.spring.StubRunnerProperties;
import org.springframework.test.context.ActiveProfiles;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Consumer-side contract test for resource-processor consuming song-service HTTP API.
 * Uses Spring Cloud Contract Stub Runner to load stubs generated by song-service producer tests.
 *
 * <p>This test verifies that resource-processor's SongServiceClient correctly communicates
 * with song-service according to the agreed contract.</p>
 *
 * <p>Contract points tested:
 * <ul>
 *   <li>POST /songs - save song metadata</li>
 * </ul>
 * </p>
 */
@SpringBootTest(
        webEnvironment = SpringBootTest.WebEnvironment.NONE,
        properties = {
                "song.service.url=http://localhost:8081",
                "resource.service.url=http://localhost:8080",
                "eureka.client.enabled=false",
                "spring.cloud.discovery.enabled=false",
                "spring.cloud.loadbalancer.enabled=false",
                "spring.rabbitmq.listener.simple.auto-startup=false",
                "spring.rabbitmq.listener.direct.auto-startup=false",
                "management.health.rabbit.enabled=false"
        }
)
@AutoConfigureStubRunner(
        ids = "com.epam.learn:song-service:+:stubs:8081",
        stubsMode = StubRunnerProperties.StubsMode.LOCAL
)
@ActiveProfiles("test")
@DisplayName("Resource Processor -> Song Service Contract Consumer Tests")
class SongServiceContractConsumerTest {

    @Autowired
    private SongServiceClient songServiceClient;

    @Test
    @DisplayName("Should save song metadata via POST /songs contract")
    void shouldSaveSongMetadataViaContract() {
        // Given - request matching the contract
        SongMetadataRequest request = SongMetadataRequest.builder()
                .id(1L)
                .name("Test Song")
                .artist("Test Artist")
                .album("Test Album")
                .duration("03:45")
                .year("2023")
                .build();

        // When - calling song-service via stub
        SongMetadataResponse response = songServiceClient.saveSongMetadata(request);

        // Then - response matches the contract
        assertThat(response).isNotNull();
        assertThat(response.getId()).isEqualTo(1L);
    }
}
