version: '3.8'

services:
  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - EUREKA_INSTANCE_HOSTNAME=eureka-server
      - EUREKA_INSTANCE_PREFERIPADDRESS=true
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8761/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  resource-db:
    image: postgres:17-alpine
    env_file: .env
    environment:
      POSTGRES_DB: ${RESOURCE_DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts/resource-db:/docker-entrypoint-initdb.d
      - resource-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${RESOURCE_DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  song-db:
    image: postgres:17-alpine
    env_file: .env
    environment:
      POSTGRES_DB: ${SONG_DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - ./init-scripts/song-db:/docker-entrypoint-initdb.d
      - song-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${SONG_DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  resource-service:
    build: ./resource-service
    env_file: .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://resource-db:5432/${RESOURCE_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      EUREKA_INSTANCE_HOSTNAME: resource-service
      EUREKA_INSTANCE_PREFERIPADDRESS: true
      SONG_SERVICE_URL: ${SONG_METADATA_SERVICE_URL}
    ports:
      - "8080:8080"
    depends_on:
      eureka-server:
        condition: service_healthy
      resource-db:
        condition: service_healthy

  song-service:
    build: ./song-service
    env_file: .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://song-db:5432/${SONG_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SERVER_PORT: 8080
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      EUREKA_INSTANCE_HOSTNAME: song-service
      EUREKA_INSTANCE_PREFERIPADDRESS: true
    ports:
      - "8081-8082:8080"
    depends_on:
      eureka-server:
        condition: service_healthy
      song-db:
        condition: service_healthy
    deploy:
      replicas: 2

volumes:
  resource-db-data:
  song-db-data:
