spring:
  application:
    name: eureka-server
  autoconfigure:
    exclude:
      - org.springframework.boot.actuate.autoconfigure.metrics.*
  cloud:
    compatibility-verifier:
      enabled: false

server:
  port: 8761

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    prefer-ip-address: ${EUREKA_INSTANCE_PREFERIPADDRESS:true}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

# Disable all metrics to avoid container issues
management:
  metrics:
    export:
      prometheus:
        enabled: false
    enable:
      all: false 